[firebase]
type = "service_account"
project_id = "agrotech-edfb5"
private_key_id = "1343041cde8ce1cc0729be34c91d52284c65134e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCi4uO1eSpXcnAA
LXfIoLz6qM6UPOuPL006WkvQxetn2hlnQMOiRaJ4DCJJVyUdK5Ev7kjKHGsTkMzm
yUlpDwfxo9TpQBCmeCQFTkjsnihGagcwuq2G1HErxKnFXQ4g1EYjxSQozRatWEpJ
qwe9cEwde8ybavDUcaR1XAeESGbIx1TXyB5U6DHT7fnpHJL+zML+mTKLBz2+l00Z
J/gwWAzKe9tiA0fPV5LmNU35w7iBh7jrl90aDSM8Gny019D7BpTBf01gtkSEtDk4
ax8hrknemFfEEqh5/thcEl1wiZhTMp4JdmI6vxj7JeEVlw76ROX1g7mRxMoaPuSu
i89wJqovAgMBAAECggEAOryHcUqqhpMZKS88KQgxbVAPAix/owfjGN4zxaqBK1dd
3rpfcXYb0p9Jg9ndY8nwlnCeJeeegxUtljFSfAR0EGJMJfo4ptbe4lzq9gxIKLAW
PK+sYFjeIHLP54AZVqRFUKPH2MCv4z1ZuHvolBrZD66zRv4Grwz1yW4wtbZn/hEy
zh1MMdVl3/1ydKCx6IcOxK2/xfrb4/9RZC/u5tbnc3J5mbYaW8oSlapZnNq0vwZt
c/PxEu4cwQAiLsNYRElcWE/9ssovddu5If0cJ+rNfRMcquVkiZghzGctdBmgdLZc
W2Q4yWG7xxSMS5FDKqTJUYSfd6oJvF4LzO+sbQKawQKBgQDlxSP6MH3fve2lvGhp
uvbdAnUNBAN3j2t/cWBqDvtBg2b8chVjBE5rXX+u192QLZNlXKp76H5LY9kcnXtC
K6/uxWjg7aThbCrP7i1tJPhj75FtEeuuFbZVwxn1jkAV6Eis3+UdVyx9s8Q4WxQ0
f4gjWDzuGpVrTx185OCDf7XxbwKBgQC1ex6yevuItG89BO4yNdLy34K3FlEloDvF
jtmut5GOY7qeeIO6iVp4YrGAklT6jtaUmoTr0wwm56IlV5OZAH1fj3zchnsoodTw
9xwFT42GvRlH3dKvdpPbZv6i1ORPrgSbB7WhywlpJHb1DEeq1WJxvwPfG3Xf/SFk
jI1eKbjzQQKBgG865lXBj832dcsb0DgO6F7JR7zLSppgdZu2WQQ+yGdIo1xmJfBP
L19OXfdYTMv1JDuXhniBblI0ve/aVMcNuxeNvV3V7VGrOXZ7SMZjdVN7sBzq5fra
S/BsiG6VNHTmg/gcUx/HCaS4l67oeHmJm2/w0V46xEa0gAPsELvX4U5FAoGAUQLX
ziZ1+C1LZrq3tbQvKXm6uQ3+RUSEygidhY+uKxi7qpfzfaZou0qbH+CyjHKMuSNM
6JR6XTeTOwYf/fGpBapgu3RQr++lxbcZTAmaDKaHDXyo2uic0hjk3D0aebMdnTLQ
0pt25PeBHpxPtaOxYUM6cDKq6MTvThor1Pfc9sECgYB0Hcha4Yatu/Z92lrDMx/R
aCmlExB2bDA/Mjp/vZQIK3w5S78q3SWg9gyLT/DOx133x/EKubgD0Ll8F1zql/rz
raZTyl92TNJYtqbwYqq3D4S3dlBDeqGuEsK5i86M+o+xXFB4NI4huKyM9hzmXoUQ
vauFOf4rCT6i+kDTpCmEUg==
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@agrotech-edfb5.iam.gserviceaccount.com"
client_id = "104139048010258388127"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40agrotech-edfb5.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
